CREATE TABLE USER_TAB (
  USER_ID INT NOT NULL,
  USERNAME VARCHAR(150) NOT NULL,
  PASSWORD VARCHAR(150) NOT NULL,
  ROLE VARCHAR(150) NOT NULL,
  PRIMARY KEY (USER_ID),
  CONSTRAINT USER_USERNAME_DX_UNIQUE UNIQUE (USERNAME)
);

CREATE TABLE SUPERIOR_TAB (
  SUPERIOR_ID INT NOT NULL,
  NAME VARCHAR(150) NOT NULL,
  USER_ID INT, 
  PRIMARY KEY (SUPERIOR_ID)
);

CREATE TABLE EMPLOYEE_TAB (
  EMPLOYEE_ID INT NOT NULL,
  NAME VARCHAR(150) NOT NULL,
  USER_ID INT, 
  SUPERIOR_ID INT NOT NULL, 
  PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE CATEGORY_TAB (
  CATEGORY_ID INT NOT NULL,
  NAME VARCHAR(150) NOT NULL,
  PRIMARY KEY (CATEGORY_ID),
  CONSTRAINT CATEGORY_NAME_DX_UNIQUE UNIQUE (NAME)
);

CREATE TABLE SHOP_TAB (
  SHOP_ID INT NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  ADDRESS VARCHAR(250) NOT NULL,
  PRIMARY KEY (SHOP_ID),
  CONSTRAINT SHOP_NAME_DX_UNIQUE UNIQUE (NAME)
);

CREATE TABLE EXPENSE_TAB (
  EXPENSE_ID INT NOT NULL,
  NAME VARCHAR(150) NOT NULL,
  TOTAL DECIMAL(9,2) NOT NULL ,
  EXPENSE_DATE DATE NOT NULL, 
  CATEGORY_ID INT NOT NULL , 
  SHOP_ID INT NULL, 
  EMPLOYEE_ID INT NOT NULL,
  STATUS ENUM('INITIAL', 'PENDING', 'APPROVED', 'REJECTED') NOT NULL,
  NOTE TEXT NULL,
  PRIMARY KEY (EXPENSE_ID)
);