-- CREATE TABLE USER_TAB (
--   USER_ID INT NOT NULL,
--   NAME VARCHAR(150) NOT NULL,
--   PRIMARY KEY (USER_ID),
--   CONSTRAINT USER_NAME_DX_UNIQUE UNIQUE (NAME)
-- );

-- CREATE TABLE CATEGORY_TAB (
--   CATEGORY_ID INT NOT NULL,
--   NAME VARCHAR(150) NOT NULL,
--   PRIMARY KEY (CATEGORY_ID),
--   CONSTRAINT CATEGORY_NAME_DX_UNIQUE UNIQUE (NAME)
-- );

CREATE test_table (
  ID INT NOT NULL,
  USER_ID INT NOT NULL,
  CATEGORY_ID INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USER_TAB (USER_ID),
  CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY_TAB (CATEGORY_ID)
);
