package spring.workshop.expenses.rest;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import spring.workshop.expenses.entities.User;
import spring.workshop.expenses.repos.UserRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class UserController {

  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewUser (@RequestParam String name) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    User n = new User(name);
    userRepository.save(n);
    return "Saved";
  }

  @DeleteMapping(path="/delete") // Map ONLY DELETE Requests
  public @ResponseBody String deleteUser (@RequestParam String name) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the DELETE request

    User entitytodelete = userRepository.findByName(name);
    userRepository.delete(entitytodelete);
    return "Deleted";
  }

  @GetMapping(path="/all")
  public @ResponseBody List<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }
}  

